### PR TITLE
 Hosted Private Cloud : New fr-fr guide for LDP in PCC Guide creation

### PR DESCRIPTION
**Pull request by pg-ovh**
Index structure coming soon.
To see past comments check : https://github.com/ovh/docs/pull/6281
- Index still pending for validation, should be in the coming days.
Update 25/06, 15:30 -> Structure validated

### CODE REVIEW

**Comment by pg-ovh** [comment]
Hello @maisonaute @poufpoufpafpaf, I have added your past comments in this version. Feel free to let me know if there is anything more that I can add in this guide. Thanks

**Comment by pg-ovh** [comment]
Hello @OVH-Team-Guides, is it possible to remove ligne 62 to 66 (included) before merging ?

```shell
For example :

1.  Kernel logs.
2.  Auth logs.
3.  Cron logs.
```
Sorry for this last minute changes :)

**Comment by OVH-Team-Guides** [comment]
@pg-ovh , I withdrew the lines you asked + the line above which made no sense alone.
I also added a disclaimer about the beta phase of the feature.
Please acknowledge if modifications are ok so that I can merge the Pull Request.

**Comment by pg-ovh** [comment]
All good @OVH-Team-Guides thanks :+1:

**Comment by OVH-Team-Guides** [comment]
Thank you for your contribution @pg-ovh

**Pull request merged**
