### PR TITLE
[ AI docs ] - add fr docs + titles/excerpts translation

### PR DESCRIPTION
**Pull request by eleapttn**
- proofread of automatic titles translations
- modifications of excerpts
- update of all the `fr-ca` + `fr-fr` docs
- translations of `product.fr-ca.md` + `product.fr-ca.md` docs

### CODE REVIEW

**Comment by fpillotovh** [comment]
Fix *deploy_guide_05_app portfolio* section, date and excerpt for FR <= Elea can you validate it plesae ?

Fix titles:

cli_13_howto_app_token_cli/guide.fr-ca.md
cli_13_howto_app_token_cli/guide.fr-fr.md
deploy_tuto_06_flask_hugging_face/guide.fr-ca.md
deploy_tuto_06_flask_hugging_face/guide.fr-fr.md
deploy_tuto_07_streamlit_eda_iris/guide.fr-ca.md
deploy_tuto_07_streamlit_eda_iris/guide.fr-fr.md
notebook_guide_data_ui/guide.fr-ca.md
notebook_guide_data_ui/guide.fr-fr.md
notebook_tuto_06_marine_mammal_sounds_classification/guide.fr-ca.md
notebook_tuto_06_marine_mammal_sounds_classification/guide.fr-fr.md
notebook_tuto_07_transfer_learning_resnet50_image_classification/guide.fr-ca.md
notebook_tuto_07_transfer_learning_resnet50_image_classification/guide.fr-fr.md

Fix excerpt 

cli_10_howto_install_cli/guide.fr-ca.md
cli_10_howto_install_cli/guide.fr-fr.md:
cli_13_howto_app_token_cli/guide.fr-ca.md
cli_13_howto_app_token_cli/guide.fr-fr.md
deploy_guide_01_capabilities/guide.fr-ca.md
deploy_guide_01_capabilities/guide.fr-fr.md
deploy_guide_05_app_portfolio/guide.fr-ca.md
deploy_guide_05_app_portfolio/guide.fr-fr.md
deploy_tuto_06_flask_hugging_face/guide.fr-ca.md
deploy_tuto_06_flask_hugging_face/guide.fr-fr.md
gi_00_ai_comparative-table/guide.fr-ca.md
gi_00_ai_comparative-table/guide.en-ie.md
gi_00_ai_comparative-table/guide.en-ca.md
gi_00_ai_comparative-table/guide.en-sg.md
gi_00_ai_comparative-table/guide.pt-pt.md
gi_00_ai_comparative-table/guide.de-de.md
gi_00_ai_comparative-table/guide.en-asia.md
gi_00_ai_comparative-table/guide.fr-fr.md
gi_00_ai_comparative-table/guide.es-us.md
gi_00_ai_comparative-table/guide.en-us.md
gi_00_ai_comparative-table/guide.pl-pl.md
gi_00_ai_comparative-table/guide.es-es.md
gi_00_ai_comparative-table/guide.en-au.md
gi_00_ai_comparative-table/guide.en-gb.md
gi_00_ai_comparative-table/guide.it-it.md
notebook_tuto_05_hugging_face_sentiment_analysis/guide.fr-ca.md
notebook_tuto_05_hugging_face_sentiment_analysis/guide.fr-fr.md
notebook_tuto_07_transfer_learning_resnet50_image_classification/guide.fr-ca.md
notebook_tuto_07_transfer_learning_resnet50_image_classification/guide.fr-fr.md
training_guide_01_capabilities/guide.fr-ca.md
training_guide_01_capabilities/guide.fr-fr.md
training_guide_02_howto_submit_job/guide.fr-ca.md
training_guide_02_howto_submit_job/guide.fr-fr.md

**Comment by fpillotovh** [comment]
I don't understand the conflicts knowing that I cloned the branch about 1 hour ago and I don't see any obvious error
The pelican checks are both good and so is the gitpod... I have the gitpod link so I can restart it and I have saved the checklinks if needed

**Comment by ovh-cds** [comment]
Failed to build static files:
```sh
{{.cds.build.pelicanoutput}}
```

**Comment by OVH-Team-Guides** [comment]
Thank you for your contribution @eleapttn and @fpillotovh

**Pull request merged**
