### PR TITLE
feat: Add notebook patch command

### PR DESCRIPTION
**Pull request by philippart-s**
Add the `patch` command for the CLI ovhai

### CODE REVIEW

**Comment by philippart-s** [comment]
@OVH-Guides-Team à priori la PR #2877 porte sur le même article, vous pouvez merge la #2877 avant et je mettrai cette PR à jour avec les nouveautés

**Comment by bs-ovh** [comment]
Heyoh!
Please resolve conflicts in #2877:
https://github.com/ovh/docs/pull/2877/conflicts

**Comment by philippart-s** [comment]
@tcpdumpfbacke conflicts are resolved, I'm waiting that the merge of the #2877 PR and then merge the develop to this PR and then re-submit this PR to review 😉

**Comment by bs-ovh** [comment]
@philippart-s Heeey, it's merged! Let me know when this one is ready.

**Comment by philippart-s** [comment]
ok, I update this PR ASAP

**Comment by philippart-s** [comment]
@tcpdumpfbacke merge done, ready to review 😉

**Pull request merged**
