### PR TITLE
Refactor endpoint to 's3.rbx-archive.io.cloud.ovh.net'

### PR DESCRIPTION
**Pull request by Pofilo**
The endpoint will be updated tomorrow (30-08-2022) in the morning.
Is it possible to wait for a GO (everything is OK on our side) before merging it ?

### CODE REVIEW

**Review by loico — APPROVED** [review]

**Comment by OVH-Team-Guides** [comment]
Hello @Pofilo, sure, please inform @Y0Coss when this is ready for a merge.

**Comment by OVH-Team-Guides** [comment]
Please update this "Last updated 15th March 2022" to "Last updated 30th August 2022"

**Review by loico — APPROVED** [review]

**Review by AymericDu — APPROVED** [review]

**Comment by Pofilo** [comment]
@Y0Coss endpoint changed, this PR is ready to merge for us.

**Comment by OVH-Team-Guides** [comment]
Thank you for your contribution @Pofilo

**Pull request merged**
