### PR TITLE
Replaced term 'Git' by 'GitHub'

### PR DESCRIPTION
**Pull request by ghost**
# Context

## Tests
| Service | Result | Proof |
|--------|--------|-------|
| https://gitlab.com | ❌ | image
| https://codeberg.org | ❌ | image
| https://gitea.com | ❌ | image
| https://code.forgejo.org | ❌ | image
| https://git.sr.ht | ❌ | image
| https://github.com | ✅ | image

## Conclusion
The term 'Git' is—_at best_—misleading, and confusing. It would be preferred to use the name 'GitHub', the only service apparently recognized.

## Remaining work
This is step 1/3 of the update.
- [x] (1/2) [On ](https://github.com/ovh/docs, replacing term 'Git' by 'GitHub' ;
- [ ] On https://github.com/ovh/manager, replacing 'Git' by 'GitHub' in button, columns, images, etc. ;
- [ ] (2/2) [On ](https://github.com/ovh/docs, replacing term 'Git' by 'GitHub'.

### CODE REVIEW

**Review by bs-ovh — APPROVED** [review]

**Comment by tcpdumpfbacke** [comment]
(To check if compatibility with other services is planned)

**Comment by ghost** [comment]
(That's why I thought at first, but the docs doesn't inform users about this, so I was thinking OVHcloud may have a partnership with GitHub or big preference for it. Thanks for feedback! Feel free to close the PR if you want. But merge 3ad135a8f14a2baec81b95329ed595661b6a1e58 at least. 😄)

**Comment by fabienOVH** [comment]
I think @GuiF008 must give his opinion. I don't know if this is a good idea knowing that Git and Github are two different things. Is this feature really only compatible with Github or is it just a front “bug” at the field level control ?

**Comment by GuiF008** [comment]
Hi, @AntoninDelFabbro 
And thx for your feedback 

This feature is a v1 that only supports Github for the moment. But the goal in the long term is to gradually add other services like Gitlab, bitbucket, etc. That's why we call them "Git". (@fabienOVH In the meantime, perhaps we could update our documents to avoid confusion).

**Comment by Y0Coss** [comment]
@AntoninDelFabbro , thank you for your contribution and interest in our solutions.
I've fixed the example URL and added information about the platforms availability on https://github.com/ovh/docs/pull/6869.
As a result, I'm closing the PR.

**Comment by ghost** [comment]
Perfect! Thank you having clarified the situation. 😄

**Pull request closed without merging**
