### PR TITLE
PGA HPC - VCD Network - Fix bad indentation on all guides VCD networking components creation

### PR DESCRIPTION
**Pull request by pg-ovh**
Add a little fix on markdown indentation for all langages guides, can be merge if ok for your @OVH-Team-Guides.
https://help.ovhcloud.com/csm/fr-vmware-vcd-network-creation?id=kb_article_view&sysparm_article=KB0063793

### CODE REVIEW

**Comment by OVH-Team-Guides** [comment]
Actually, the indentation is currently good. 
On the very vast majority of our guides, the template is the following:
```
## Objective
## Requirements
## Instructions
### Step 1
### Step 2
## Go further
```
The actual steps are always depending from the `## Instructions` part, so they are H3, not H2.

**Comment by OVH-Team-Guides** [comment]
So there is actually one mistake on the current version of the guide.
The `## Step 2 - Create a datacentre group (optional)` should be `### Step 2 - Create a datacentre group (optional)`
Can you revert your changes and do this fix instead?

**Comment by pg-ovh** [comment]
I looks weird on the site, are you shur @OVH-Team-Guides ? I think all steps should be at the same levels, because it also brakes the right menu.
Should I put ###Step1/2/3 ?

-
Selection_060
Selection_061

**Comment by OVH-Team-Guides** [comment]
Yes, I am sure. The "Step2" indentation should be fixed (from ## to ###), not the other steps.

**Comment by pg-ovh** [comment]
Well is it possible to have them at the same level, like this ?
```
## Objective
## Requirements
## Instructions
### Step 1
### Step 2
### Step 3
### Step 4
## Go further
```

**Comment by OVH-Team-Guides** [comment]
Yes, that's the right layout. To do that, as mentioned in my previous comment, the `## Step 2 - Create a datacentre group (optional)` should bed edited into `### Step 2 - Create a datacentre group (optional)`.
And you should revert your intial changes on this PR.

**Comment by pg-ovh** [comment]
Anyway, I'll fix the issue yes by adding ### on every step.

-
Screenshot from 2024-07-17 15-31-09

**Review by OVH-Team-Guides — APPROVED** [review]

**Comment by OVH-Team-Guides** [comment]
Thank you for your contribution @pg-ovh

**Pull request merged**
