### PR TITLE
Object Storage - Local Zones specifications - SK-1652

### PR DESCRIPTION
**Pull request by Y0Coss**
- Creating a new page to list Local Zones specifications for Object Storage
- Updating the Object Storage limitations page to include a features availability matrix between Regions and LZ

@lason-ovh , please review EN and FR versions for technical accuracy. Please also challenge the new guide title in FR and EN and feel free to suggest an excerpt (guide meta-description).

### CODE REVIEW

**Review by lason-ovh — CHANGES_REQUESTED** [review]
As discussed with Mirko and Eddy, table in s3_compliancy should be updated to display an additional column "local zones" and "Features availability" in s3_local_zones_limitations should link to s3_compliancy page

**Comment by Y0Coss** [comment]
> As discussed with Mirko and Eddy, table in s3_compliancy should be updated to display an additional column "local zones" and "Features availability" in s3_local_zones_limitations should link to s3_compliancy page

That's already here

**Review by lason-ovh — APPROVED** [review]
ok pour moi

**Comment by Y0Coss** [comment]
@lason-ovh , @agoude , updates are done following our meeting today.

**Pull request merged**
