### PR TITLE
Changing reference to user management menu

### PR DESCRIPTION
**Pull request by gbarideau**
Following MANAGER-12811, user guide have been updated to refer to the new user management menu
This update has to be sync with the manager update

### CODE REVIEW

**Comment by OVH-Team-Guides** [comment]
To Do : 

- Translations for other languages
- Date update when ETA is confirmed

**Comment by OVH-Team-Guides** [comment]
@gbarideau , can you please double-check that the PL translation of "Identities" in the manager is "Identifier", and the PT translation is "Identitades" ?

**Comment by gbarideau** [comment]
Correction of PL and PT translation done

**Comment by OVH-Team-Guides** [comment]
Thank you for your contribution @gbarideau

**Pull request merged**
