### PR TITLE
[AI General Information] - update titles

### PR DESCRIPTION
**Pull request by eleapttn**
To be more precise in the naming of the titles in "General Information" section of AI docs, some doc titles have been updated: 

For `en` docs (duplicates done 🌍 ✅ ):
- [FAQ AI training](https://help.ovhcloud.com/csm/en-gb-public-cloud-ai-faq?id=kb_article_view&sysparm_article=KB0048202) => **FAQ - AI training**
- [Comparative tables between AI Notebooks, AI Training, AI Deploy](https://help.ovhcloud.com/csm/en-gb-public-cloud-ai-comparative-tables?id=kb_article_view&sysparm_article=KB0048165) => **Comparative tables - AI Notebooks, AI Training, AI Deploy**
- [Use & manage existing and new registries](https://help.ovhcloud.com/csm/en-gb-public-cloud-ai-cli-manage-registries?id=kb_article_view&sysparm_article=KB0057949) => **Registries - Use & manage registries**
- [ovhai CLI Cheat Sheet](https://help.ovhcloud.com/csm/en-gb-public-cloud-ai-cheat-sheet?id=kb_article_view&sysparm_article=KB0048221) => **ovhai CLI - Cheat Sheet**

For `fr` docs (duplicates done 🇫🇷 ✅ ):
- [FAQ AI Training (EN)](https://help.ovhcloud.com/csm/fr-public-cloud-ai-faq?id=kb_article_view&sysparm_article=KB0048206) => **FAQ - AI Training (EN)**
- [Tableaux comparatifs entre AI Notebooks, AI Training, AI Deploy (EN)](https://help.ovhcloud.com/csm/fr-public-cloud-ai-comparative-tables?id=kb_article_view&sysparm_article=KB0048159) => **Tableaux comparatifs - AI Notebooks, AI Training, AI Deploy (EN)**
- [Utiliser et gérer vos registres (EN)](https://help.ovhcloud.com/csm/fr-public-cloud-ai-manage-registries?id=kb_article_view&sysparm_article=KB0057958) => **Registres - Utiliser et gérer vos registres (EN)**

`index.yaml` updated ✅
_dates_ updated ✅

### CODE REVIEW

**Comment by ovh-cds** [comment]
Failed to build static files:
```sh
/tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/plugins/ovh_filters/translator.py:15: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.translations = yaml.load(fd)
/tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/plugins/ovh_filters/banner.py:15: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.banners = yaml.load(fd)
WARNING: Empty alt attribute for image img_2903.jpg in /tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/pages/web/domains/glue_registry/guide.nl-nl.md
WARNING: Empty alt attribute for image img_2900.jpg in /tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/pages/web/domains/glue_registry/guide.nl-nl.md
WARNING: Empty alt attribute for image img_2901.jpg in /tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/pages/web/domains/glue_registry/guide.nl-nl.md
WARNING: Empty alt attribute for image img_2902.jpg in /tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/pages/web/domains/glue_registry/guide.nl-nl.md
WARNING: Other images have empty alt attributes
  File "/tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/plugins/ovh_markdown/blocksprocessor.py", line 303, in run
    tabs = self.build_tabs_object(lines)
  File "/tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/plugins/ovh_markdown/blocksprocessor.py", line 280, in build_tabs_object
    if line[0] != ">":
  File "/tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/plugins/ovh_markdown/blocksprocessor.py", line 303, in run
    tabs = self.build_tabs_object(lines)
  File "/tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/plugins/ovh_markdown/blocksprocessor.py", line 280, in build_tabs_object
    if line[0] != ">":
ERROR: Could not process /tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/pages/platform/ai/gi_00_ai_comparative-table/guide.es-us.md
  | ScannerError: while scanning an alias
  in "<unicode string>", line 9, column 1:
    **Last updated 12th May, 2023.**
    ^
expected alphabetic or numeric character, but found '*'
  in "<unicode string>", line 9, column 2:
    **Last updated 12th May, 2023.**
     ^
CRITICAL: RuntimeError: Error encountered
```

**Review by MathieuBsqt — APPROVED** [review]
Perfect! 

Idea: I would maybe add a `T` uppercase letter to `FAQ - AI training` to make it `FAQ - AI Training`, in the ìndex.md` file and in the `gi_04_training_FAQ` guides.

**Comment by eleapttn** [comment]
Thanks @MathieuBsqt for the review.

The modification has been done ✅

🚀

**Comment by OVH-Team-Guides** [comment]
Thank you for your contribution @eleapttn

**Pull request merged**
