### PR TITLE
Hosted Private Cloud : Remove Federation guides (vs IAM)

### PR DESCRIPTION
**Pull request by pg-ovh**
Still waiting for the feedback to remove this Baremetal guide : https://help.ovhcloud.com/csm/fr-managed-bare-metal-federation?id=kb_article_view&sysparm_article=KB0044445

### CODE REVIEW

**Comment by OVH-Team-Guides** [comment]
To merge after PR #6264 and once related 301s (to write) are merged by GPIO

**Comment by pg-ovh** [comment]
Hello @OVH-Team-Guides I have removed the ref to the federation folder guides, let me know if there is anything else I can do.

**Comment by OVH-Team-Guides** [comment]
Please do not make unrelated commits.

**Comment by OVH-Team-Guides** [comment]
Thank you for your contribution @pg-ovh

**Pull request merged**
