### PR TITLE
feat(clouddb): add web hosting network to clouddb guide

### PR DESCRIPTION
**Pull request by wdhif**
Adding the new Web Hosting network feature for CloudDB in our guides.

### CODE REVIEW

**Comment by wdhif** [comment]
Waiting for Manager feature deployment.

**Comment by BrenKt** [comment]
**Waiting** the feature "Access to OVHcloud web hosting" (Authorised IPs) into manager before merge

**Comment by wdhif** [comment]
> **Waiting** the feature "Access to OVHcloud web hosting" (Authorised IPs) into manager before merge

Merged and now in production.

**Comment by ovh-cds** [comment]
Failed to build static files:
```sh
{{.cds.build.pelicanoutput}}
```

**Comment by ovh-cds** [comment]
Failed to build static files:
```sh
{{.cds.build.pelicanoutput}}
```

**Comment by OVH-Team-Guides** [comment]
Thanks for your contribution @wdhif

**Pull request merged**
