### PR TITLE
[Managed Kubernetes] - feat: Pulsar with streamnative tutorial

### PR DESCRIPTION
**Pull request by OVH-Team-Guides**
Article written by Streamnative team (@jak78) and tested by @philippart-s.
Originally created in https://github.com/ovh/docs/pull/4920 and now ready to be prodded.

### CODE REVIEW

**Comment by OVH-Team-Guides** [comment]
Thanks for your contribution @philippart-s

**Comment by jak78** [comment]
@OVH-Team-Guides Thank you for merging! Could you please tell me what the next step will be? Is there a scheduled doc release?

**Comment by OVH-Team-Guides** [comment]
Hello @jak78, this will be published later today. I will share the link with you here.

**Comment by OVH-Team-Guides** [comment]
The documentation is now published https://help.ovhcloud.com/csm/en-gb-public-cloud-kubernetes-installing-pulsar?id=kb_article_view&sysparm_article=KB0058940
Thank you for your contribution @jak78

**Comment by jak78** [comment]
Great, thank you @OVH-Team-Guides !

**Pull request merged**
