### PR TITLE
fix(ldp): remove opensearch 2.x upgrade guide

### PR DESCRIPTION
**Pull request by pdepaepe**
Hello,

This PR to 

- remove the `OpenSearch 2.X` upgrade guide (as it has been done six month ago).
- point to 2.X release on `Grafana & LDP` documentation.

As always, thank you for your time on this.

### CODE REVIEW

**Comment by Y0Coss** [comment]
Hello @pdepaepe , the Grafana guide had been updated a few months ago by the US team. Somehow, only the en-gb version had been updated, I'm duplicating this missing update on all versions, which results into your update on that guide not being needed anymore.
I found another link to the upgrade guide into the Filebeat guide. Please check if deleting the whole warning is ok.

I've also prepared 301 rules for the deleted guide to be redirected (upcoming PR on the related GPIO repo).

**Comment by Y0Coss** [comment]
Note: 301 rules added on the GPIO repository ( PR 5838)

**Comment by Y0Coss** [comment]
Thank you for your contribution @pdepaepe

**Comment by DoStupidThingsFasterWithMoreEnergy** [comment]
> [!NOTE]
> no `excerpt` key in frontmatter

**Pull request merged**
