### PR TITLE
Hpc - VCD migration guide update and fix

### PR DESCRIPTION
**Pull request by pg-ovh**
Guide fix and updates.

### CODE REVIEW

**Comment by pg-ovh** [comment]
Hello @OVH-Team-Guides, I have remove the changes from vcd get concepts guide from this PR for your information.

**Comment by Y0Coss** [comment]
> Hello @OVH-Team-Guides, I have remove the changes from vcd get concepts guide from this PR for your information.

@pg-ovh , what you did is a deletion of the file. That may not be what you intended to do.

**Comment by pg-ovh** [comment]
> > Hello @OVH-Team-Guides, I have remove the changes from vcd get concepts guide from this PR for your information.
> 
> @pg-ovh , what you did is a deletion of the file. That may not be what you intended to do.

Yes I just want to remove the folder from the PR and all changes made to the guide (VCD concepts), not remove the guide from the website.

**Comment by Y0Coss** [comment]
> > > Hello @OVH-Team-Guides, I have remove the changes from vcd get concepts guide from this PR for your information.
> > 
> > 
> > @pg-ovh , what you did is a deletion of the file. That may not be what you intended to do.
> 
> Yes I just want to remove the folder from the PR and all changes made to the guide (VCD concepts), not remove the guide from the website.

Then you need to add the fr-fr file again in its folder. The guide version must be the one from the develop branch.

**Comment by Y0Coss** [comment]
Thank you for your contribution @pg-ovh

**Pull request merged**
