### PR TITLE
Domains & DNS - DNS guides titles update

### PR DESCRIPTION
**Pull request by fabienOVH**

### CODE REVIEW

**Comment by OVH-Team-Guides** [comment]
Using https://www.highervisibility.com/seo/tools/serp-snippet-optimizer/

- "Configurer un enregistrement DKIM pour améliorer la sécurité des emails" is too long to be SEO compliant
- Same for "Configurer un enregistrement DMARC pour améliorer la sécurité des emails"
- Same for "Configurer un enregistrement SPF pour améliorer la sécurité des emails"
For those 3 titles, I recommended removing "pour améliorer la sécurité des e-mails" (please note: e-mails in FR, not emails) from the title and adding it into the excerpts.

- "Comment supprimer une zone DNS ?" is more SEO compliant (many customers look for "How to" / "Comment.." titles) than only "Supprimer une zone DNS". Why changing it ?

**Comment by OVH-Team-Guides** [comment]
Other title suggestion which is < 580px:

- "Améliorer la sécurité des emails via un enregistrement DKIM" (same title for SPF / DMARC)
- EN version: "Improve email security with a DKIM record"

**Comment by Marcodauphin** [comment]
OK fabien as discussed

**Review by OVH-Team-Guides — APPROVED** [review]

**Comment by OVH-Team-Guides** [comment]
Thank you for your contribution @fabienOVH

**Pull request merged**
