### PR TITLE
EN - Typo - Managed Kubernetes Documentation

### PR DESCRIPTION
**Pull request by fduthilleul**
Added the missing m in examples.

### CODE REVIEW

**Comment by cortexx** [comment]
Hello @fduthilleul 

Could you also fix this typo in the following pages?
* `guide.en-asia.md`
* `guide.en-au.md`
* `guide.en-ca.md`
* `guide.en-ie.md`
* `guide.en-sg.md`

Currently, the i18n/l18n system isn't used so these are some duplicate content but we need to keep all the pages up to date.

Thanks for your PR :)

**Comment by fduthilleul** [comment]
Hello @cortexx 

I fixed the different pages including guide.en-gb.md
I committed directly in the develop branch. 
Let me know if it is OK and if there was a more optimal way to do it.
Kind Regards,
François

**Comment by OVH-Team-Guides** [comment]
Hi @fduthilleul,
Thanks for that contribution. Your current pull request only includes the en-gb edition so far.
If you have edited the other english versions, please do another pull request. If there are issues, please tell us, we'll be able to do the duplicates.
Best regards,
The OVHcloud guides team

**Comment by OVH-Team-Guides** [comment]
Merge is done, thanks for your contribution.

**Comment by fduthilleul** [comment]
> Hi @fduthilleul,
> Thanks for that contribution. Your current pull request only includes the en-gb edition so far.
> If you have edited the other english versions, please do another pull request. If there are issues, please tell us, we'll be able to do the duplicates.
> Best regards,
> The OVHcloud guides team

Hi ! I edited the other english versions yesterday. Should I redo the changes or can I find my changes back ? Should I create a PR for each change or there is a way to include all changes in one PR ? Thanks for your guidance :)

François

**Comment by OVH-Team-Guides** [comment]
You probably did the changes only on your fork. You now can do a new PR which includes all these changes.

**Pull request merged**
