### PR TITLE
Update VPS guide - Shipyard article

### PR DESCRIPTION
**Pull request by iamarya2k24**
Shipyard is no longer maintained, hence users should be discouraged from using it.

### CODE REVIEW

**Comment by iamarya2k24** [comment]
This is my first commit to your repo, let me know if any correction is needed or if you have any suggestions.
Regards,
Navneet

**Comment by bs-ovh** [comment]
Edited to apply our regular warning message format

**Comment by bs-ovh** [comment]
Thank you for your contribution, Navneet!

**Comment by iamarya2k24** [comment]
@tcpdumpfbacke My pleasure! ^_^

**Pull request merged**
