### PR TITLE
Update for LBaaS GA release

### PR DESCRIPTION
**Pull request by mhurtrel**
Please prod once LbaaS is released only (check with M.Peresse).

### CODE REVIEW

**Review by LostInBrittany — APPROVED** [review]

**Review by OVH-Team-Guides — APPROVED** [review]
PR is approved. Changes will need to be applied also to other EN versions.
Prod scheduled for April 10th.

**Comment by mhurtrel** [comment]
@OVH-Guides-Team No please abort; As stated in my PR "Please prod once LbaaS is released only (check with M.Peresse)."

**Comment by OVH-Team-Guides** [comment]
> @OVH-Guides-Team No please abort; As stated in my PR "Please prod once LbaaS is released only (check with M.Peresse)."

Loud and clear, we won't move until you tell us to.

**Review by d33d33 — APPROVED** [review]

**Comment by OVH-Team-Guides** [comment]
Merge on develop is done. Thanks for your contribution.

**Pull request merged**
