### PR TITLE
feat: link to new vrack gw guide

### PR DESCRIPTION
**Pull request by scraly**

### CODE REVIEW

**Comment by Jessica41** [comment]
Hello @scraly is it possible to adjust the vrack link on all subs, they all redirect to the UK website.

**Comment by scraly** [comment]
Sorry, I fixed links.

**Comment by ovh-cds** [comment]
Failed to build static files:
```sh
{{.cds.build.pelicanoutput}}
```

**Comment by OVH-Team-Guides** [comment]
Thanks for your contribution @scraly

**Pull request merged**
