### PR TITLE
  Add the new Kubernetes / vRack / How to use custom Gateway tutorial

### PR DESCRIPTION
**Pull request by raclepoulpe**
Add the new Kubernetes / vRack / How to use custom Gateway tutorial

### CODE REVIEW

**Comment by scraly** [comment]
I will do a complete review on Monday 🙂

**Review by scraly — APPROVED** [review]
review, edit, add images, improved the documentation

**Comment by scraly** [comment]
Approved, to be released :)

**Comment by bs-ovh** [comment]
Thank you!

**Pull request merged**
