### PR TITLE
Hosted Private Cloud :  En-gb trad for user access read only vxlans mode to NSX-T pcc guide

### PR DESCRIPTION
**Pull request by pg-ovh**

### CODE REVIEW

**Review by bs-ovh — CHANGES_REQUESTED** [review]
There are differences between EN & FR versions. Plz verify (mostly in the FR file):
- Image placement and file names
- Missing text parts
- Proper instructions on the pages

**Comment by pg-ovh** [comment]
Hello @OVH-Team-Guides I have added the modifications on the FR guide and rename the image that I changed on it. Let me know if you need more help. Edition done.

**Review by bs-ovh — APPROVED** [review]

**Review by bs-ovh — APPROVED** [review]
EN version good

**Review by OVH-Team-Guides — APPROVED** [review]

**Comment by OVH-Team-Guides** [comment]
Thank you for your contribution @pg-ovh

**Pull request merged**
