### PR TITLE
PUPI-647 : Fix Broken links in web-paas

### PR DESCRIPTION
**Pull request by somi99-byte**
Fixing Broken links in

1. administration-web/configure-environment/guide.en*
2. administration-web/guide.en*
3. frameworks-drupal7/migrating/guide.en*

### CODE REVIEW

**Comment by ovh-cds** [comment]
Failed to build static files:
```sh
{{.cds.build.pelicanoutput}}
```

**Comment by ovh-cds** [comment]
Failed to build static files:
```sh
{{.cds.build.pelicanoutput}}
```

**Comment by ovh-cds** [comment]
Failed to build static files:
```sh
{{.cds.build.pelicanoutput}}
```

**Comment by OVH-Team-Guides** [comment]
Thanks for your contribution @somi99-byte. Merge on master will be done soon.

**Pull request merged**
